build:
  script: "cargo test"
  tags:
    - rust
pages:
  script:
    - cargo doc
    - rm -rf target/doc/libc
    - rm -rf target/doc/bitflags
    - rm -rf target/doc/src/libc
    - rm -rf target/doc/src/bitflags
    - mv target/doc public
  artifacts:
    paths:
    - public
  only:
  - master
  tags:
  - rust
